name: PictureMe
favicon: null
layout_spectrum: 0.74245
typography_spectrum: 0.1412459
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc7ed'
    - '#100e17'
    - '#6f93b5'
    - '#dce8f1'
    - '#61574f'
  brandStrength: 0.25
  lightness: 0.1025778
  saturation: 0.75
  rhythmicContrast: 0.9199785
purpose: []
