favicon: null
name: Picture Me
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5257788
  brandStrength: 1
  lightness: 0.4978518
  brandColors:
    - '#011F02'
    - '#FCFBFB'
    - '#B43931'
    - '#6E9177'
    - '#F1BD5D'
  rhythmicContrast: 0.5558539
typography_spectrum: 0.1412459
layout_spectrum: 0.4656284
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
